### ISSUE TITLE
Is the API down?

### ISSUE THREAD

**Issue by connorraikar** [ncpierson/soundoftext#15]
I am getting timeout errors. Is the API currently down?

**Comment by ncpierson** [comment]
Hi, yes, it has been spotty lately.

I migrated soundoftext to a new server, and I did not configure the memory correctly. I plan on fixing it soon.

**Comment by connorraikar** [comment]
Thanks! I look forward to it, it’s been such a cool and convenient tool for my studying.

**Comment by ncpierson** [comment]
For reference, there is a status page for sound of text here: http://status.soundoftext.com

I just reconfigured parts of the deployment, so hopefully we'll see a more steady uptime today.
If not, I'll keep trying fixes later this week.

**Comment by ncpierson** [comment]
Had to increase memory from 1GB to 2GB on the server (for an additonal $5/month 😕) but it seems to be holding steady now.
I didn't expect soundoftext.com was going to experience this type of growth again 😅
